# Docker Compose Configuration for Carbon Footprint Monitor
# Run with: docker-compose up -d
# Stop with: docker-compose down

version: '3.8'

services:
  # =========================================================================
  # FLASK BACKEND SERVICE
  # =========================================================================
  backend:
    # Build from Dockerfile in current directory
    build:
      context: .
      dockerfile: Dockerfile
    
    # Container name
    container_name: carbon-monitor-backend
    
    # Ports mapping (host:container)
    ports:
      - "5000:5000"
    
    # Environment variables
    environment:
      # Flask Configuration
      FLASK_ENV: production
      FLASK_APP: app.py
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
      SECRET_KEY: ${SECRET_KEY:-change-this-secret-key-in-production}
      
      # Database Configuration
      DATABASE_FILE: /app/data/emissions.json
      
      # ML Model Configuration
      MODEL_PATH: /app/models/emission_model.pkl
      
      # CORS Configuration
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      
      # Logging Configuration
      LOG_LEVEL: INFO
      LOG_FILE: /app/logs/app.log
    
    # Volume mounts (persistent storage)
    volumes:
      # Data persistence
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./exports:/app/exports
    
    # Auto-restart policy
    restart: unless-stopped
    
    # Network
    networks:
      - carbon-network
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Depends on
    depends_on:
      - redis
    
    # Resource limits (optional)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 512M
    #     reservations:
    #       cpus: '0.5'
    #       memory: 256M

  # =========================================================================
  # REDIS CACHE SERVICE (Optional - for performance)
  # =========================================================================
  redis:
    # Redis image
    image: redis:7-alpine
    
    # Container name
    container_name: carbon-monitor-redis
    
    # Ports
    ports:
      - "6379:6379"
    
    # Volumes
    volumes:
      - redis_data:/data
    
    # Commands
    command: redis-server --appendonly yes --requirepass redispass123
    
    # Restart policy
    restart: unless-stopped
    
    # Network
    networks:
      - carbon-network
    
    # Health check
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =========================================================================
  # NGINX REVERSE PROXY (Optional - for production)
  # =========================================================================
  nginx:
    # Nginx image
    image: nginx:alpine
    
    # Container name
    container_name: carbon-monitor-nginx
    
    # Ports
    ports:
      - "80:80"
      - "443:443"
    
    # Volumes
    volumes:
      # Nginx configuration
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      
      # SSL certificates (optional)
      # - ./ssl/cert.pem:/etc/nginx/ssl/cert.pem:ro
      # - ./ssl/key.pem:/etc/nginx/ssl/key.pem:ro
      
      # Static files
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
    
    # Environment
    environment:
      UPSTREAM_HOST: backend
      UPSTREAM_PORT: 5000
    
    # Depends on backend
    depends_on:
      - backend
    
    # Networks
    networks:
      - carbon-network
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =========================================================================
  # POSTGRESQL DATABASE (Optional - for future use)
  # =========================================================================
  # db:
  #   image: postgres:15-alpine
  #   
  #   container_name: carbon-monitor-db
  #   
  #   environment:
  #     POSTGRES_DB: carbon_monitor
  #     POSTGRES_USER: ${DB_USER:-carbon}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-change-password}
  #   
  #   ports:
  #     - "5432:5432"
  #   
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   
  #   networks:
  #     - carbon-network
  #   
  #   restart: unless-stopped
  #   
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U carbon"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

# =========================================================================
# VOLUMES DEFINITION
# =========================================================================
volumes:
  redis_data:
    driver: local
  # postgres_data:
  #   driver: local

# =========================================================================
# NETWORKS DEFINITION
# =========================================================================
networks:
  carbon-network:
    driver: bridge

# =========================================================================
# USAGE INSTRUCTIONS
# =========================================================================
# 
# BUILD & START CONTAINERS:
#   docker-compose up -d
#
# VIEW LOGS:
#   docker-compose logs -f backend
#
# STOP CONTAINERS:
#   docker-compose down
#
# REMOVE VOLUMES:
#   docker-compose down -v
#
# REBUILD IMAGES:
#   docker-compose up -d --build
#
# ACCESS APPLICATION:
#   http://localhost:5000
#   http://localhost (via Nginx)
#
# DATABASE:
#   Stored in: ./data/emissions.json
#   Backups in: ./backups/
#
# LOGS:
#   App logs: ./logs/app.log
#   Docker: docker-compose logs
#
# =========================================================================